environment:
  mode: "development"
database:
  type: mysql
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 2