<?php
/**
 * Copyright (C) 2020 - 2023 | Valiant Network / Matthew Jordan
 *
 * This program is private software. You may not redistribute this software, or
 * any derivative works of this software, in source or binary form, without
 * the express permission of the owner.
 *
 * @author sylvrs
 */
declare(strict_types=1);

namespace essence\translation;

/**
 * This class was automatically generated by /scripts/generate_translations.php
 * Do not edit this file manually.
 */
final class EssenceTranslationKeys {
	public const COMMAND_SETROLE_FAILURE = "command.setrole.failure";
	public const COMMAND_SETROLE_PLAYER_MUST_JOIN = "command.setrole.player_must_join";
	public const COMMAND_SETROLE_INVALID_ROLE = "command.setrole.invalid_role";
	public const COMMAND_SETROLE_PLAYER_NOT_FOUND = "command.setrole.player_not_found";
	public const COMMAND_SETROLE_SUCCESS = "command.setrole.success";
	public const COMMAND_SETROLE_UPDATED_ROLE = "command.setrole.updated_role";
	public const CHAT_FORMAT = "chat.format";
	public const SERVER_JOIN_XBOX_REQUIRED = "server.join.xbox_required";

	private function __construct() {
	}
}
